# Generated by Django 5.1.6 on 2025-10-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vendor_vendordeliverysettings_vendorwarehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordeliverysettings',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='vendordeliverysettings',
            name='delivery_regions',
        ),
        migrations.CreateModel(
            name='RegionDeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('vendor_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_prices', to='account.vendordeliverysettings')),
            ],
            options={
                'verbose_name': 'Цена доставки по региону',
                'verbose_name_plural': 'Цены доставки по регионам',
                'unique_together': {('vendor_settings', 'region_name')},
            },
        ),
    ]
