# Generated by Django 5.1.6 on 2025-10-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_vendordeliverysettings_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default=1, max_length=40, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
