# Generated by Django 5.1.6 on 2025-10-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vendor_vendordeliverysettings_vendorwarehouse'),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendorwarehouse'),
        ),
        migrations.DeleteModel(
            name='VendorDeliverySettings',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorWarehouse',
        ),
    ]
