# Generated by Django 5.1.6 on 2025-11-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_vendor_address_vendor_email_vendor_phone_number'),
        ('magazine', '0002_remove_vendor_user_alter_productoffer_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.vendor', verbose_name='продавец'),
            preserve_default=False,
        ),
    ]
