# Generated by Django 5.1.6 on 2025-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидочная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость товара'),
        ),
    ]
