# Generated by Django 5.1.6 on 2025-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_product_discounted_price_product_regular_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productviewhistory',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ключ сессии'),
        ),
    ]
